name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo fmt -- --check

  warnings:
    name: Warnings
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo rustc -- -D warnings
    - run: cargo clippy -- -D warnings

  tests:
    name: Cargo Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo test --verbose

  wasmtest:
    name: Wasm Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - run: wasm-pack test --chrome --headless

  wasmbench:
    name: Wasm Bench
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - run: ./tool/benchmark | tee > wasm-bench.txt
    - uses: actions/upload-artifact@v2
      with:
        name: wasm-bench.txt
        path: wasm-bench.txt

  wasmsize:
    name: Wasm Size
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - run: sudo apt-get install brotli
    - run: ./tool/release.sh
    - run: ./tool/release.sh --report > wasm-size.txt
    - uses: actions/upload-artifact@v2
      with:
        name: wasm-size.txt
        path: wasm-size.txt
